Repository mul-meong/backend-contest-read, pull requests merged in 2024-12, with the labels that each got.

#4 [🚀 Contest-Read] CI/CD 환경 구축
  .github/workflows/cicd.yaml
  Dockerfile
  build.gradle
  src/main/java/com/mulmeong/contestread/common/exception/BaseException.java
  src/main/java/com/mulmeong/contestread/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/contestread/common/response/BaseResponse.java
  src/test/java/com/mulmeong/contestread/ContestReadApplicationTests.java
Labels: 👷 chore, 🚀 deploy

#2 [🔀 Contest-Read] contest read db 갱신
  build.gradle
  src/main/java/com/mulmeong/contest/read/ContestReadApplication.java
  src/main/java/com/mulmeong/contest/read/application/ContestPostService.java
  src/main/java/com/mulmeong/contest/read/application/ContestPostServiceImpl.java
  src/main/java/com/mulmeong/contest/read/application/KafkaConsumer.java
  src/main/java/com/mulmeong/contest/read/common/config/KafkaConsumerConfig.java
  src/main/java/com/mulmeong/contest/read/common/config/SwaggerConfig.java
  src/main/java/com/mulmeong/contest/read/common/exception/BaseException.java
  src/main/java/com/mulmeong/contest/read/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/contest/read/common/healthcheck/healthcheck/HealthCheckController.java
  src/main/java/com/mulmeong/contest/read/common/response/BaseResponse.java
  src/main/java/com/mulmeong/contest/read/common/response/BaseResponseStatus.java
  src/main/java/com/mulmeong/contest/read/common/utils/CursorPage.java
  src/main/java/com/mulmeong/contest/read/domain/document/ContestPost.java
  src/main/java/com/mulmeong/contest/read/domain/document/ContestVote.java
  src/main/java/com/mulmeong/contest/read/domain/model/Media.java
  src/main/java/com/mulmeong/contest/read/domain/model/MediaInfo.java
  src/main/java/com/mulmeong/contest/read/domain/model/MediaSubtype.java
  src/main/java/com/mulmeong/contest/read/domain/model/MediaType.java
  src/main/java/com/mulmeong/contest/read/domain/model/SortType.java
  src/main/java/com/mulmeong/contest/read/dto/in/ContestPostRequestDto.java
  src/main/java/com/mulmeong/contest/read/dto/model/BasePaginationRequestDto.java
  src/main/java/com/mulmeong/contest/read/dto/out/ContestPostResponseDto.java
  src/main/java/com/mulmeong/contest/read/infrastructure/ContestPostCustomRepository.java
  src/main/java/com/mulmeong/contest/read/infrastructure/ContestPostRepository.java
  src/main/java/com/mulmeong/contest/read/infrastructure/ContestVoteRepository.java
  src/main/java/com/mulmeong/contest/read/presentation/ContestPostController.java
  src/main/java/com/mulmeong/event/contest/consume/ContestPostCreateEvent.java
  src/main/java/com/mulmeong/event/contest/consume/ContestVoteRecordEvent.java
  src/main/java/com/mulmeong/event/contest/consume/ContestVoteUpdateEvent.java
  src/test/java/com/mulmeong/contest/read/ContestReadApplicationTests.java
Labels: ✨ enhancement

#5 [🚀 Contest-Read] contest readDB 기능 구현
  build.gradle
  src/main/java/com/mulmeong/contest/read/ContestReadApplication.java
  src/main/java/com/mulmeong/contest/read/application/ContestPostService.java
  src/main/java/com/mulmeong/contest/read/application/ContestPostServiceImpl.java
  src/main/java/com/mulmeong/contest/read/application/KafkaConsumer.java
  src/main/java/com/mulmeong/contest/read/common/config/KafkaConsumerConfig.java
  src/main/java/com/mulmeong/contest/read/common/config/SwaggerConfig.java
  src/main/java/com/mulmeong/contest/read/common/exception/BaseException.java
  src/main/java/com/mulmeong/contest/read/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/contest/read/common/healthcheck/healthcheck/HealthCheckController.java
  src/main/java/com/mulmeong/contest/read/common/response/BaseResponse.java
  src/main/java/com/mulmeong/contest/read/common/response/BaseResponseStatus.java
  src/main/java/com/mulmeong/contest/read/common/utils/CursorPage.java
  src/main/java/com/mulmeong/contest/read/domain/document/ContestPost.java
  src/main/java/com/mulmeong/contest/read/domain/document/ContestVote.java
  src/main/java/com/mulmeong/contest/read/domain/model/Media.java
  src/main/java/com/mulmeong/contest/read/domain/model/MediaInfo.java
  src/main/java/com/mulmeong/contest/read/domain/model/MediaSubtype.java
  src/main/java/com/mulmeong/contest/read/domain/model/MediaType.java
  src/main/java/com/mulmeong/contest/read/domain/model/SortType.java
  src/main/java/com/mulmeong/contest/read/dto/in/ContestPostRequestDto.java
  src/main/java/com/mulmeong/contest/read/dto/model/BasePaginationRequestDto.java
  src/main/java/com/mulmeong/contest/read/dto/out/ContestPostResponseDto.java
  src/main/java/com/mulmeong/contest/read/infrastructure/ContestPostCustomRepository.java
  src/main/java/com/mulmeong/contest/read/infrastructure/ContestPostRepository.java
  src/main/java/com/mulmeong/contest/read/infrastructure/ContestVoteRepository.java
  src/main/java/com/mulmeong/contest/read/presentation/ContestPostController.java
  src/main/java/com/mulmeong/event/contest/consume/ContestPostCreateEvent.java
  src/main/java/com/mulmeong/event/contest/consume/ContestVoteRecordEvent.java
  src/main/java/com/mulmeong/event/contest/consume/ContestVoteUpdateEvent.java
  src/test/java/com/mulmeong/contest/read/ContestReadApplicationTests.java
Labels: 🚀 deploy

#7 [🚑️ Contest-Read] 의존성 에러 Resolve
  build.gradle
Labels: 🐛 bug

#8 [🚑️ Contest-Read] 의존성 에러 Resolve
  build.gradle
Labels: 🐛 bug

#10 [🚑️ contest-read] base response 수정
  src/main/java/com/mulmeong/contest/read/common/response/BaseResponse.java
  src/main/java/com/mulmeong/contest/read/common/response/BaseResponseStatus.java
Labels: 🚑️ hotfix

#9 [🚑️ contest-read] base response 수정
  src/main/java/com/mulmeong/contest/read/common/response/BaseResponse.java
  src/main/java/com/mulmeong/contest/read/common/response/BaseResponseStatus.java
Labels: 🚑️ hotfix
